### PR TITLE
Implement support for multiple languages

### LINKED ISSUE #34: Ignore errors on non-PowerShell files
If I understand correctly, PSEdit is analyzing PowerShell script files for errors. But it shouldn't assume that every file is a PowerShell file. I have a JSON file open in the editor, and I shouldn't get errors. 
image

This can be misleading for less experienced users.

### PR DESCRIPTION
**Pull request by halvarsson**
Raising this as a PR as its a large change, would be nice if I could get a review and maybe some help with testing that everything works as intended 😀

This PR fixes #34, as it adds support for JSON files, and it also implement a basic editor for non-supported file extensions

I implemented a concept of EditorContext, which provides the editor functionality with everything disabled by default, where we then map a specific editor context for languages by file extensions. The Editor Context will produce a dictionary with points to colors based on the parsing, and we cache this when you use the editor

It should be fairly simple to add support for additional languages in the future as well.

For Powershell we support it the same as before, and I split all powershell logic to the editorcontext. On JSON I added syntax highlighting, formatting and error parsing.

I also added an entry to the status bar indicating what language we interpret the file as

The editor remains Powershell by default, and the support for other types is only applicable when either passing a file to psedit, or when opening a file from the editor

I ended up using Newtonsoft.Json for the JSON parsing instead of System.Text.Json as I kept running into reference errors when using it in Powershell 5.1. The current implementation should work for both 5/7

EditorContext

### CODE REVIEW

**Comment by halvarsson** [comment]
@adamdriscoll, could you help review these changes? The PR is the same size as your initial commit of the project so it would be nice with another set of eyes :) Might be time for a new release too! I am also working on adding support for other formats like XML etc.

**Comment by adamdriscoll** [comment]
@halvarsson I will take a look at this tomorrow! Thanks for putting this together!!

**Comment by halvarsson** [comment]
@adamdriscoll, bump :-)

**Comment by En3Tho** [comment]
@adamdriscoll can you take a look at this? I just found this editor and it's so nice. Yaml support would be nice to have too.

**Pull request merged**
